stages:
  - build

build master:
  stage: build
  only:
    - master
  image: "docker:git"
  services:
    - docker:dind
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/spiel/notification-center:latest
  script:
    - docker build --force-rm --tag $CONTAINER_RELEASE_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker logout $CI_REGISTRY
    - docker rmi $CONTAINER_RELEASE_IMAGE

build develop:
  stage: build
  only:
    - develop
  image: "docker:git"
  services:
    - docker:dind
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/spiel/notification-center:dev
  script:
    - docker build --force-rm --tag $CONTAINER_RELEASE_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker logout $CI_REGISTRY
    - docker rmi $CONTAINER_RELEASE_IMAGE

build tags:
  stage: build
  only:
    - tags
  image: "docker:git"
  services:
    - docker:dind
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/spiel/notification-center:$CI_COMMIT_TAG
  script:
    - docker build --force-rm --tag $CONTAINER_RELEASE_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker logout $CI_REGISTRY
    - docker rmi $CONTAINER_RELEASE_IMAGE
